### ISSUE TITLE
Dogecoin support

### ISSUE THREAD

**Issue by haccel** [in3rsha/bitcoin-utxo-dump#14]
It doesn't work.

`
Total UTXOs: 5856992

Total BTC: 0.000
`

 Can you implement it or just give me a hint how to do it.
Thank you

**Comment by in3rsha** [comment]
I'm afraid I have no idea how the chainstate database in Dogecoin works. I'm open to pull requests to support other coins, but it's not something I would work on.

**Comment by jacektrocinski** [comment]
@anders-hoovy I'm working on a Dogecoin fork if you're interested: https://github.com/jacektrocinski/dogecoin-utxo-dump/tree/develop

**Comment by mrx23dot** [comment]
Looks like the repo doesn't exist anymore :(

**Comment by jacektrocinski** [comment]
> Looks like the repo doesn't exist anymore :(

I took it down since it wasn't fully implemented, when I have some more time I might bring it back.
