### ISSUE TITLE
Is there way I can also get the timestamp of UTXO?

### ISSUE THREAD

**Issue by TurtleJelly** [in3rsha/bitcoin-utxo-dump#15]
Hello Sir,

I am wondering if there's anyway to extract the timestamp of UTXO as well.

Thanks in advance!

**Comment by in3rsha** [comment]
The UTXO database doesn't contain a timestamp alongside the transactions unfortunately.

However, it does contain the `height` of the block it was mined in to, and each block contains a Unix timestamp, so you could use that to get a rough (and only) timestamp for a transaction.

For example, here's how you could find the timestamp for the block at height `123,456` using `bitcoin-cli`:

```
bitcoin-cli getblock $(bitcoin-cli getblockhash 123456) | grep '"time"'
```
