### ISSUE TITLE
Too many BTC in circulation?

### ISSUE THREAD

**Issue by RemcoMi** [in3rsha/bitcoin-utxo-dump#16]
I have a fullnode running from where I copy the chainstate to a new folder to run this script against.

Result of various dumps:
```
Total UTXOs: 66632964
Total BTC:   18481045.05567317

Total UTXOs: 66632964
Total BTC:   18481045.05567317

Total UTXOs: 66632964
Total BTC:   18481045.05567317

Total UTXOs: 66592544
Total BTC:   18479582.45596703

Total UTXOs: 66529362
Total BTC:   18485795.13070076

Total UTXOs: 66552445
Total BTC:   18488411.92702591

Total UTXOs: 66554994
Total BTC:   18460739.06478096

Total UTXOs: 66530417
Total BTC:   18542498.44333380

Total UTXOs: 66325016
Total BTC:   18472223.00121369

Total UTXOs: 66461702
Total BTC:   18496591.51414967

Total UTXOs: 66472668
Total BTC:   18497154.38937850
```

The total amount of btc seems to be overstated compared to other sources:
https://statoshi.info/dashboard/db/unspent-transaction-output-set
https://www.blockchain.com/charts/total-bitcoins
https://coinmarketcap.com/currencies/bitcoin/ (circulating supply)

How is that possible?

**Comment by RemcoMi** [comment]
Even on the normal chainstate with bitcoin-d stopped:
Total UTXOs: 66606486
Total BTC:   18492764.67662761

root@server:~# bitcoin-cli gettxoutsetinfo
{
  "height": 645126,
  "bestblock": "0000000000000000000fc68b828f684b2200e1a21a6eb1f6c46842e6b902cff5",
  "transactions": 40887628,
  "txouts": **66579042**,
  "bogosize": 5000877023,
  "hash_serialized_2": "6ad5342b4d6f2fff9d6fad538ec68e8647dba7e3b36e6adc4a4574fe8aece8dd",
  "disk_size": 4070079865,
  "total_amount": **18469360.87854892**
}

**Comment by RemcoMi** [comment]
Thanks for your reply!

I let my node re-index all blocks and the current output is correct.
I'll take a closer look the coming days!

I would like to start saving data about the UTXO set. As I would like to keep my node running for other tasks while running the dump script, I copy the whole chainstate.

Might it be possible to do a UTXO dump of say 1 month ago using the current chainstate? Or does it only save the currenct UTXO's?

**Comment by in3rsha** [comment]
No problem, glad it worked out.

This tool just reads whatever is currently in the chainstate database.

If you want to get a snapshot of the UTXO set for a specific point in time, a blockchain parser like [`bitcoin-iterate`](https://github.com/rustyrussell/bitcoin-iterate) would be a better option.

**Comment by RemcoMi** [comment]
In my last run the amount of btc was too low. 
I think I can't overcome stopping the node and running the tool then on the actual chainstate.. Until now that worked well, so probably the copied chainstate isn't correct as files are being edited.

My node is re-indexing again as I runned the tool before bitcoind finished the stop command which corrupted files.
