### ISSUE TITLE
bitcoin-utxo-dump: command not found

### ISSUE THREAD

**Issue by a-wertheim** [in3rsha/bitcoin-utxo-dump#17]
Hi in3rsha - great work on this!

I'm on a Mac and have gone through the installation process up until running $bitcoin-utxo-dump. When doing so I get "command not found". I had to get around "sudo apt install libleveldb-dev" by using "brew install libleveldb" instead (without -dev, since it can't be found via brew), so I'm not sure if this is what's causing the issue but the binary seems to have been created when running "go get github.com/in3rsha/bitcoin-utxo-dump" - it just isn't found for some reason. Any ideas?

Thanks! - Andrew

**Comment by jackneil** [comment]
the binary ends up being just utxo-dump ... not bitcoin-utxo-dump

**Comment by in3rsha** [comment]
Sorry for the delay @a-wertheim. Does @jackneil's answer help you?

I'm not on a Mac so I haven't been able to create install instructions for this tool.

**Comment by a-wertheim** [comment]
Hi All,

Yes I believe that would have solved the problem as well. Instead, I ended up doing a Finder search fro the binary and ran it just fine. For some reason it was downloaded into an obscure location, which took some digging to find. It ran great, though. Thank you again for the project. If I get some time, I might be able to streamline a Mac implementation. I don't have much time these days, but if I get around to it, that would be useful.
