### ISSUE TITLE
utxo csv missing some fields

### ISSUE THREAD

**Issue by jackyxie** [in3rsha/bitcoin-utxo-dump#18]
After execute the export command and save data to csv file. I found that some fields are missing, such as address.

![20201010122728](https://user-images.githubusercontent.com/3347704/95645678-0ceba580-0af4-11eb-8fa3-c20c680fdb7b.png)

**Comment by in3rsha** [comment]
Hi @jackyxie 

Not all UTXOs have addresses. The UTXOs in your screenshot have multisig (p2ms) locks on them, and whilst they contain public keys, they scripts themselves do not actually have their own address format.

These are the only locking scripts placed on UTXOs that have addresses:

* **P2PKH** (1address)
* **P2SH** (3address)

* **P2WPKH** (bc1address, 42 characters)
* **P2WSH** (bc1address, 62 characters)

**Comment by jackyxie** [comment]
thanks, get it.
