### ISSUE TITLE
bitcoin-utxo-dump: command not found

### ISSUE THREAD

**Issue by camielzz** [in3rsha/bitcoin-utxo-dump#20]
Dear sir, I think and hope this will be an easy fix and I'm 99.9% sure this is my bad, but when i try to run "bitcoin-utxo-dump" it gives me a command not found error. I ran the command in various locations including the folder where the executable file is located. I'm aware that there is a similar issue that has been closed already, but that didn't help me fix my issue. If I open the executable it does give me a csv file with the utxo's but i cant use any parameters, i need the block height included. Also a version where height is printed in default will help me fix my issue.

Thanks in advance,
Camiel

**Comment by in3rsha** [comment]
I'm running Linux and I haven't had the opportunity to test this on Mac, so my help is limited I'm afraid. It sounds like it might be something to do with being able to find golang executables on Mac (e.g. GOPATH or something), so you may be able to find more answers by searching in that area.

Alternately, if you can find the `utxodump.go` file and edit this line:

```
fields := flag.String("f", "count,txid,vout,amount,type,address", "Fields to include in output. [count,txid,vout,height,amount,coinbase,nsize,script,type,address]")
```

To this:

```
fields := flag.String("f", "count,txid,vout,amount,type,address,height", "Fields to include in output. [count,txid,vout,height,amount,coinbase,nsize,script,type,address]")
```

You can then run the script directly with `go run utxodump.go` and it will give you the height for each UTXO.

But I think the best option would be to find out how to add the location of Go binaries to your PATH.

**Comment by camielzz** [comment]
I have fixed it, thanks!!
