### ISSUE TITLE
dump utxo data different with rpc data.

### ISSUE THREAD

**Issue by jackyxie** [in3rsha/bitcoin-utxo-dump#22]
I found that use this tool dump out data is less than the data it should be. As the follow I execute the tool and then at the same time get data from rpc.

bitcoin-utxo-dump final result
```
Total UTXOs: 73333114
Total BTC:   18642162.20453415
Script Types:
 p2wpkh       4044781
 p2wsh        298623
 non-standard 9540
 p2pk         61206
 p2pkh        54670818
 p2sh         13828327
 p2ms         681935
```

bitcoin-cli getmempoolinfo
```
{
  "height": 674001,
  "bestblock": "00000000000000000007f8d1652e3bf35c9d2672be4834fef6ebc6f1c407bd8c",
  "transactions": 44795401,
  "txouts": 73360127,
  "bogosize": 5498036952,
  "hash_serialized_2": "7ac46aa0d60b6be1eef2f66e099e8dc8589fd9400792b14697a3361407e15ae6",
  "disk_size": 4935108151,
  "total_amount": 18649807.38006601
}
```

**Comment by jackyxie** [comment]
I found that hdd disk is easy to showup (has to be reindex to resume), but ssd disk is correct.

**Comment by in3rsha** [comment]
Sorry for the late reply, are you still having any issues?

For what it's worth this tool will work on a snapshot of the current chainstate database, so the "live" results you get when using bitcoin-cli commands will probably differ slightly.
