### ISSUE TITLE
Dogecoin support

### ISSUE THREAD

**Issue by Napulsnik** [in3rsha/bitcoin-utxo-dump#23]
Hello. Thanks for the great tool. Is it possible to add support for other similar cryptocurrencies? Interested in Dogecoin.

**Comment by in3rsha** [comment]
I'm not actively working on this tool at the moment so I haven't got the time to add support for other cryptocurrencies I'm afraid.

However, if the cryptocurrency is a fork of Bitcoin, there is a decent chance it will use the same structure for its chainstate database (where the UTXOs are stored).

You could try pointing this tool at Dogecoin's chainstate folder (wherever it's located) using this option:

```
bitcoin-utxo-dump -db ~/.dogecoin/chainstate/
```

I'm not sure if it will work, but it might be worth a shot. It would probably require writing a completely new tool if it doesn't.

**Comment by Napulsnik** [comment]
> I'm not actively working on this tool at the moment so I haven't got the time to add support for other cryptocurrencies I'm afraid.
> 
> However, if the cryptocurrency is a fork of Bitcoin, there is a decent chance it will use the same structure for its chainstate database (where the UTXOs are stored).
> 
> You could try pointing this tool at Dogecoin's chainstate folder (wherever it's located) using this option:
> 
> ```
> bitcoin-utxo-dump -db ~/.dogecoin/chainstate/
> ```
> 
> I'm not sure if it will work, but it might be worth a shot. It would probably require writing a completely new tool if it doesn't.

Hello. I've tried this already. Here is the result:

Total UTXOs: 6534349
Total BTC:   0.00000000
Script Types:
 p2ms         0
 p2wpkh       0
 p2wsh        0
 non-standard 0
 p2pk         0
 p2pkh        0
 p2sh         0

**Comment by mrx23dot** [comment]
As I started debugging it the prefixes are 'c' meaning it uses v0.14 old core.
Is there a description how to parse those values?
