### ISSUE TITLE
Active bitcoind warning even if a copy of the chainstate folder is selected.

### ISSUE THREAD

**Issue by streamofstars** [in3rsha/bitcoin-utxo-dump#24]
bitcoin-utxo-dump does not work when bitcoind is running. I am aware this is by design. However, the problem is that the tool does not want to work when bitcoind is running even if I provide a path to a copy of the chainstate folder which is not currently used by any instance of bitcoind and which was copied before, while bitcoind was not running. I suggest replacing the current behavior with a warning and a user prompt if a user wishes to continue, as I recon, detecting if selected folder is an actual bitcoind database or just a copy might be difficult. If this is implemented, I would also appreciate a switch for ignoring this warning, so it can be used programmatically.

**Comment by in3rsha** [comment]
That makes sense. Didn't consider that this tool might be used programmatically.

I've added a prompt asking if you wish to continue anyway if bitcoind is running, and added the `-nowarnings` flag to completely ignore this warning if you wish.

Thanks for the suggestion.
