### ISSUE TITLE
Losing utxo data on bitcoinsv

### ISSUE THREAD

**Issue by hustxiaoc** [in3rsha/bitcoin-utxo-dump#3]

**Comment by in3rsha** [comment]
Can you tell me more about the problem you are having?

I only designed this tool to work on the Bitcoin UTXO database, but I'm assuming that BitcoinSV is a direct fork so I'd be interested to see what error you are getting.

If you are not getting any results, you may need to point the tool at a different directory with:

```
bitcoin-utxo-dump -db /path/to/your/chainstate/folder
```

**Comment by hustxiaoc** [comment]
I didn't get any errors,  lots of utxo data are just missing.

**Comment by in3rsha** [comment]
When you tried it on different machines was it always against a BitcoinSV chainstate database?

Also, could you post an example of some of the results you are getting?

**Comment by hustxiaoc** [comment]
Yeah, all BitcoinSV chainstate database. You can't find anything wrong with the results unless you compute the results with another way. I find something wrong because I've run it with sparkSQL before.

**Comment by in3rsha** [comment]
I would assume that Bitcoin SV is using a different type of chainstate database schema. I do not run Bitcoin SV so I am not able to check.

I am closing this issue for now as I designed this tool to work for Bitcoin (and not for other coins and their chainstate databases I'm afraid).
