### ISSUE TITLE
Incorrect satoshi value for Litecoin

### ISSUE THREAD

**Issue by pancakeflip** [in3rsha/bitcoin-utxo-dump#31]
Hi in3rsha, thank you for the great tool!

I am trying to get a list of UTXOs for Litecoin. Everything is in order except the satoshi values. Do I have to change anything in order to get the correct amount in satoshi?

**Comment by in3rsha** [comment]
No problem.

I haven't tried this tool with anything other than Bitcoin. What problem are you seeing with the values?

**Comment by pancakeflip** [comment]
The available balance of the addresses are very far off from its actual value. Below is the first three address with balance and its amount in satoshi.

![Capture](https://user-images.githubusercontent.com/92006496/148308032-2deb58d6-4c3d-4091-b610-aecf9d3e156b.PNG)

By using an online SATS to LTC calculator, the balance in LTC is as follows.

![image](https://user-images.githubusercontent.com/92006496/148308406-62c4cca5-3cf9-440a-be3d-714601c63a4f.png)

However, Litecoin explorer displayed different values for all the three addresses. The correct balance is shown in the image below.

![image](https://user-images.githubusercontent.com/92006496/148308620-5642bf51-eba6-4ff6-9d59-792d25c82c2f.png)
![image](https://user-images.githubusercontent.com/92006496/148308652-c9b3f976-3500-4637-81f4-d00e64220564.png)
![image](https://user-images.githubusercontent.com/92006496/148308689-937eb2dc-06f4-456e-ba33-b8daad5f88c0.png)

Since Litecoin is a hard fork of Bitcoin with both having the same chainstate database structure, shouldn't it work for Litecoin as well? Everything is in order (txid, vout, type, address) except the amount. Am I doing anything wrong?

**Comment by in3rsha** [comment]
I'm closing this issue for now. I primarily only wrote this tool to work with Bitcoin, and I don't have the time to make it work for other coins too I'm afraid.

Feel free to make a pull request if you think you can make it more universal for coins that are similar to Bitcoin.
