### ISSUE TITLE
bug with address-type

### ISSUE THREAD

**Issue by jcodic** [in3rsha/bitcoin-utxo-dump#33]
I was browsing your code and found a bug, so look:

script := xor[offset:]

// P2PKH
if nsize == 0 {
 
   [some code]

   scriptType = "p2pkh"
   scriptTypeCount["p2pkh"] += 1
}

// P2MS
if len(script) > 0 && script[len(script)-1] == 174 { // if there is a script and if the last opcode is OP_CHECKMULTISIG (174) (0xae)

   scriptType = "p2ms"
   scriptTypeCount["p2ms"] += 1
}

So any p2pkh address with last byte of hash == 174 will be overwritten as 'p2ms', which is not. It should be switch like.

**Comment by ottosch** [comment]
I guess this example confirms it:
`68b78781b48ab059cae5cd1ec061f0245250edcbabe172d4dff44978ec358d06,0,572449,p2ms,578d1837461b0894e30ea2c9e53a71b98b85e0ae,18yvp7agsCA54JrQxxhjaEnjRBdPoVGbit`

**Comment by in3rsha** [comment]
Thank you both, I've changed the `if` statements to a `switch` statement.

I don't think my current method of looking for a single `0xAE` (`174`) byte at the end is the perfect way to identify a P2MS script, but at least this change means it won't overwrite any P2PKH scripts as being P2MS anymore.

Thanks again for pointing this out.
