### ISSUE TITLE
Original COINBASE (Newly Generated Coins) transactions does not include the address, only txid and amount

### ISSUE THREAD

**Issue by 2595raven** [in3rsha/bitcoin-utxo-dump#34]
Command used: 
bitcoin-utxo-dump -db Backupchainstate/ -f txid,address,amount -o btc_test.txt

example output from btc_test.txt
749fa48af8fab93ee1d8d3f32c4aef147686d394d4725d938cfcd634844c8103,1Ak4TzLZ4pgKYHpr5GontQgoDqwQunAK6c,50000000000
fc7185f9ab7b90161c9b4f6f59fa96e158c671225717e74093a08de5c88e8103,,5000000000
8695751953a8bda3328ab3c14b67c503a4884d323d1fe2887423b7c2a0898203,,5000000000
8769b385bd62d1bf31f6bd8f5868dfcee7798d2f0afb0f535e38295f4aef8203,,5000000000
2c7605bebf15ed82490d2a1fde57bedb9d8de81db38336d2194f1467c8ca8503,,5000000000
1642e0b6243ad8c14f73ddbd8b1d59c1b27fa8edc3527767c0eceb4161118603,,5000000000
2421bcfae5eb1abcaf2224d236bfb72f1a4f730243cd2ab16c0675d822498803,,5000000000
eb016d74bbdc1d1e3debd83d00d352b67e74c051600992a92d0df8d54ff18903,,5000000000
7ab361114598d72857947e721b767fe8e6f0fab577fae547275dea14a7608a03,,5000000000

If any of the txid's with no address is checked in blockexplorer it will show as an initial mining coin transaction.

Is there a switch in this great application that can be used to show the address of these transactions?

**Comment by in3rsha** [comment]
**Quick answer:**

Yep, use the `-p2pkaddresses` flag:

```
bitcoin-utxo-dump -db Backupchainstate/ -f txid,address,amount -p2pkaddresses -o btc_test.txt
```

**Quick explanation:**

These early coinbase transactions (for collecting the block reward) don't technically have an address.

They use an early form of locking script called "P2PK", which contain a public key, but do not have their own address format.

However, you can take this public key and use to to create an address as if the locking script was the more common "P2PKH" type.

So the `-p2pkaddresses` flag will allow you to search for these outputs in some block explorers, but just be aware that these block explorers are showing addresses for outputs that do not technically have an address in real life.

P.S. Thanks for the kind words.

**Comment by 2595raven** [comment]
Thanks for the quick reply,

I did an update - go get github.com/in3rsha/bitcoin-utxo-dump and bitcoin-utxo-dump was recreated in my system.
When running with this flag I get an error:
flag provided but not defined: -p2pkaddresses
Usage of ../go/bin/bitcoin-utxo-dump:
-db string
etc..

Any other update I miss?

Regards

**Comment by 2595raven** [comment]
Please ignore previous message.
Ensured everything updated and then the flag was accepted.

**Comment by 2595raven** [comment]
Result now is 100% as expected.
Thanks again for the quick reply.
I am closing the issue
