### ISSUE TITLE
Couldn't find /.bitcoin/chainstate/

### ISSUE THREAD

**Issue by phum126** [in3rsha/bitcoin-utxo-dump#4]
Trying to run bitcoin-utxo-dump, but getting an error stating 

```"Couldn't find /.bitcoin/chainstate/"```

Ive changed default folder to:

```defaultfolder := fmt.Sprintf("I:/Bitcoin/bitcoin/chainstate/", os.Getenv("HOME"))```

But getting same error?

Using Windows 10, my primary drive is C:/.

**Comment by in3rsha** [comment]
Could you try running the tool from the command line using the `-db` option:

```
$ bitcoin-utxo-dump.go -db /path/to/chainstate
```

I don't run Windows so I haven't been able to test this I'm afraid. Could you try that out with a few reasonable-looking paths (relative to whatever `os.Getenv("HOME")` might be on Windows) to see if anything works?

**Comment by in3rsha** [comment]
> `defaultfolder := fmt.Sprintf("I:/Bitcoin/bitcoin/chainstate/", os.Getenv("HOME"))`

Another potential fix: doesn't windows use backslashes `\` for directories?
