### ISSUE TITLE
I reimplemented it in typescript

### ISSUE THREAD

**Issue by Overtorment** [in3rsha/bitcoin-utxo-dump#44]
hello, i reimplemented this tool in typescript here: https://github.com/Overtorment/bitcoin-utxo-dump-ts
just fyi.
thanks for your work!

**Comment by in3rsha** [comment]
No problem, and nice.

Is this for a feature in BlueWallet?

**Comment by Overtorment** [comment]
no, but i have a few ideas how this can be used, for example, electrum server that bootstraps very fast
