### ISSUE TITLE
address is missing for some txs

### ISSUE THREAD

**Issue by digitalik** [in3rsha/bitcoin-utxo-dump#5]
Take a look at tx 0e3e2357e806b6cdb1f70b54c3a3a17b6714ee1f0e68bebb44a74b1efd512098 (block 1). All elements are there except address:

`[root@tmp-1-fra bin]# cat utxodump.csv | grep 0e3e2357e806b6cdb1f70b54c3a3a17b6714ee1f0e68bebb44a74b1efd512098
36012933,0e3e2357e806b6cdb1f70b54c3a3a17b6714ee1f0e68bebb44a74b1efd512098,0,5000000000,p2pk,
[root@tmp-1-fra bin]#`

**Comment by digitalik** [comment]
got it. it is not possible to get address from pubkey

**Comment by richie-rich-ai** [comment]
I'm also having the same problem. I didn't get this. How come we can't get address from pubkey? Address is calculated from pubkey right?

Blockchain shows address for the same tx: https://www.blockchain.com/btc/tx/0e3e2357e806b6cdb1f70b54c3a3a17b6714ee1f0e68bebb44a74b1efd512098

But this program gives out empty...

**Comment by in3rsha** [comment]
> I'm also having the same problem. I didn't get this. How come we can't get address from pubkey? Address is calculated from pubkey right?
> 
> Blockchain shows address for the same tx: https://www.blockchain.com/btc/tx/0e3e2357e806b6cdb1f70b54c3a3a17b6714ee1f0e68bebb44a74b1efd512098
> 
> But this program gives out empty...

A public key doesn't always have an address. An address actually corresponds with a specific type of locking script, and the public key is contained within that locking script.

For example, the address `` corresponds to the following P2PKH locking script:

```
```
