### ISSUE TITLE
All btc

### ISSUE THREAD

**Issue by beiex** [in3rsha/bitcoin-utxo-dump#7]
Hi and thanks 4 the great work!

I ran this against my full node and it said at the end there where like 2,3 million unspent btc in chainstate.
should this not add up to the 18 million btc created till today..? lost or not they have to be bound in some kind of unspent UTXO.. right ? Or is there something I'm not thinking of or don't know ;-)
it doesn't show multi-sig addresses but since there is a sat amount... 
so where are the other 15,7 mil btc

Edit:
On further inspection my file is 1.01 GB .. not 7.xx
then I thought I had a file size limitation so I ran -f amount,address and the file was about 350mb
so i waited and ran against a newer chainstate and the UTXO count and the btc amount went up
now I have 8529954 UTXO's and 2.39 million btc as of mon 18, nov 2019
before I had a UTXO count of 8242975 and 2.29 million btc
therefore I don't think it stops prematurely.. 

any ideas?
ps: b core is running on newest Mac OS and the .go was also run on Mac OS

**Comment by in3rsha** [comment]
Interesting. I just ran `bitcoin-utxo-dump` with no options and ended up with the following results:

```
Total UTXOs: 63145928
Total BTC:   18056017.32163399
Script Types:
 p2pkh        52125175
 p2sh         9786443
 p2ms         647600
 p2wpkh       661915
 p2wsh        79370
 non-standard 9522
 p2pk         63560
```

I don't have a Mac so I'm not able to troubleshoot I'm afraid. My guess would be that you may not be pointing to the correct chainstate database on your Mac. Try finding where your chainstate is and running:

```
bitcoin-utxo-dump.go -db /path/to/chainstate/
```

Other than that, you have a completely synced full Bitcoin Core node yes?

**Comment by beiex** [comment]
are you on linux or windows?
yes its a fully synced 0.18.1 btc core full node with 290GB blockchain running..
interestingly since I copied the chainstate from my server where it's running onto my dev system (both Mac OS )  I thought maybe don't use a copy but the real thing and did a network share to the btc drive.. we'll there it ran even shorter with only 1.4 mil btc showing. that is very confusing...
(both when copying and parsing I did shut down btc core correctly b4 hand)
I since moved my btc core to my dev Mac and deleted the entire chainstate folder content.. resyncing now in the hopes that it had something to do with the files themselves.
will edit here when that's done .. 

btw. when push comes to shove do u have a decent inet connection? would u be willing to push me u'r .csv file so I can make a diff and get a starting point to debug it?

**Comment by beiex** [comment]
ok, I found the problem .. and just now the solution.. will post tomorrow

**Comment by beiex** [comment]
Long story short, I suspected some kind of file handling problem according to the behaviour I saw.
After debugging and omitting the file buffer to do so: Turns out that with or without write buffer there is a limit on file operations per second.
In macOS it is set to 1024 by default and on linux to the max 4096 by default.

So to run this correctly on macOS

`ulimit -n 4096; go run bitcoin-utxo-dump.go; ulimit -n 1024`

I tried to implement this in code

`import "runtime"      // Check OS type for file-handler limitations`

```
// Check if OS type is Mac OS, then increase ulimit -n to 4096 filehandler during runtime and reset to 1024 at the end
// Mac OS standard is 1024
// Linux standard is already 4096 wich is also "max" for more edit etc/security/limits.conf
	if runtime.GOOS == "darwin" {
             cmd2 := exec.Command("ulimit", "-n", "4096")
             fmt.Println("setting ulimit 4096\n", err)
             _, err2 := cmd2.Output()
             if err2 != nil {
                 fmt.Println("setting new ulimit failed with %s\n", err)
             }
             defer exec.Command("ulimit", "-n", "1024")
	}
```

don't know if that's completely correct or worth a commit but seems to be working for me.

**Comment by in3rsha** [comment]
Wow, nice work. Thank you.

Would you consider adding this as a pull request? I haven't got a Mac so wouldn't be able to test, but the code does look good.

**Comment by beiex** [comment]
You'r welcome and THANK YOU for the solid code! ;-)
Hope the Pull Request is working.. Is it correct that I "have to fork" before hand?

**Comment by beiex** [comment]
nice homepage btw. :-D

**Comment by streamofstars** [comment]
Has this been implemented already? If so, it may not be working as desired. I tested it today on MacOS 11.3.1 (x86 CPU) and chainstate from Bitcoin Core 0.21.1 and it returns less than 8m UTXOs. I can see it prints to console
```
setting ulimit 4096
 exit status 1
```
so I guess it tries but for some reason it does not work. I also attempted running it with sudo with the same effect. However, when I manually set `ulimit -n 4096` and then run normally (and aftewards re-set `ulimit -n 256`) it returned 75m UTXOs.

**Comment by beiex** [comment]
Hi, yeah it was working up to some random macOS update in Catalina when they prepared the move to macOS 11 Big S. They deprecated something.. haven’t gotten around to looking into that. If I find the time I will look into this in the next few weeks..
