### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by RedGuitar0** [in3rsha/bitcoin-utxo-dump#8]
hey
 i need the addresses's file (have all the bitcoin' address).
but i tried many times ,it' s can be ture ,cant install leveldb.
im not pro.
could i get your addresses file
thanks

**Comment by beiex** [comment]
it's 2.2 GB

**Comment by RedGuitar0** [comment]
Can I use FTP to upload to the virtual host, and then I'll log in and download your email, I'll send my account and login password。
